feat: добавить резолюцию для User и Item
AndreyDenisov0197/java-shareit pull request #1
Opened 2024-02-05 18:41 UTC by AndreyDenisov0197

2024-02-06 09:32 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    private final UserStorage userStorage;
userStorage здесь лишний

2024-02-06 09:34 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") int userId,
На входе и выходе методов контроллеров должны быть только объекты Dto

2024-02-06 09:37 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
Классы контроллера и стораджа тоже бы по пакетам разложить

2024-02-06 09:38 UTC, VadimZharkov requested changes
Нет никакой валидации для объектов Dto. Нужно добавить. Желательно с помощью аннотаций

2024-02-06 18:08 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    private final UserStorage userStorage;
done

2024-02-06 18:54 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
done

2024-02-06 18:55 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") int userId,
В Usere также?

2024-02-06 20:34 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") int userId,
Сделал ещё под User на всякий случай, если в дальнейшем добавятся поля

2024-02-06 20:39 UTC, AndreyDenisov0197 commented
Привет, если есть ещё рекомендации как можно улучшить, буду рад получить совет

2024-02-07 11:03 UTC, VadimZharkov approved these changes

2024-02-07 15:16 UTC, merged