feat: добавить бронирование
AndreyDenisov0197/java-shareit pull request #2
Opened 2024-02-24 15:08 UTC by AndreyDenisov0197

2024-02-25 09:16 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +                                                                    LocalDateTime now1,
now1 - не удачное название.  Во первых now может быть только одно.  И в принципе название переменных с цифрой считается плохой практикой, т.к. цифра не несет смысла. Можно переменные назвать yfghbvth after и start

2024-02-25 09:17 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +                                                                    LocalDateTime now1,
тоже самое про название переменных

2024-02-25 09:19 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ExeptionHandler.java
> +
Нужно добавить перехват всех остальных эксепшенов Throwable в статус INTERNAL_SERVER_ERROR

2024-02-25 09:20 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ExeptionHandler.java
> +    public ResponseEntity<String> notFoundHandle(Exception e) {
Вместо ResponseEntity лучше сделать отдельный класс ErrorResponse и во всех методах хэндлера отдавать его.

2024-02-25 09:23 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ExeptionHandler.java
> +
Также добавить обработку MethodArgumentNotValidException и ValidationException в BAD_REQUEST.
Эти эксепшены могут возникать при валидации с помощью аннотаций

2024-02-25 09:27 UTC, VadimZharkov requested changes
Можно улучшить

2024-02-25 10:29 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +                                                                    LocalDateTime now1,
done

2024-02-25 10:30 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +                                                                    LocalDateTime now1,
done

2024-02-25 10:32 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/exception/ExeptionHandler.java
> +
done

2024-02-25 10:38 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/exception/ExeptionHandler.java
> +
done

2024-02-25 10:45 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/exception/ExeptionHandler.java
> +    public ResponseEntity<String> notFoundHandle(Exception e) {
done

2024-02-26 05:55 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ExeptionHandler.java
> +    public ErorrResponse<String> notFoundHandle(Exception e) {
Имелась ввиду след. реализация.

`public class ErrorResponse {
	private final String error;

	public ErrorResponse(String error) {
		this.error = error;
	}

	public String getError() {
		return error;
	}
}`

и

```
	@ExceptionHandler
	@ResponseStatus(HttpStatus.NOT_FOUND)
	public ErrorResponse handleNotFoundException(final NotFoundException e) {
		log.info("404 {}", e.getMessage());
		return new ErrorResponse(e.getMessage());
	}
```

2024-02-26 05:58 UTC, VadimZharkov requested changes
Нужно еще немного доработать

2024-02-27 06:21 UTC, VadimZharkov approved these changes

2024-03-01 12:36 UTC, merged