Add item requests
AndreyDenisov0197/java-shareit pull request #3
Opened 2024-03-05 20:39 UTC by AndreyDenisov0197

2024-03-07 05:54 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/pageRequest/MyPageRequest.java
> +public class MyPageRequest extends PageRequest {
Нет никакой необходимости делать не стандартную пагинацию. Вполне можно обойтись существующими классами

2024-03-07 05:59 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceDb.java
> +public class RequestServiceDb implements RequestService {
В реализации нет зависимостей от конкретной Db, только от интерфейсов репозиториев. Поэтому не нужно в название сервиса вкладывать зависимость от Db. Лучше назвать   RequestServiceImpl

2024-03-07 06:02 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/request/controller/RequestController.java
> +                                         @RequestParam(required = false, defaultValue = "0") @Min(0) int from,
required = false противоречит defaultValue = "0", т.к. значение будет всегда

2024-03-07 06:06 UTC, VadimZharkov reviewed
Не увидел тестов Dto с помощью `@JsonTest`

2024-03-07 06:07 UTC, VadimZharkov requested changes
Нужно доработать

2024-03-07 09:07 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/pageRequest/MyPageRequest.java
> +public class MyPageRequest extends PageRequest {
Done

2024-03-07 09:08 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/pageRequest/MyPageRequest.java
> +public class MyPageRequest extends PageRequest {
Done

2024-03-07 09:11 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceDb.java
> +public class RequestServiceDb implements RequestService {
Done

2024-03-07 09:16 UTC, AndreyDenisov0197 commented on src/main/java/ru/practicum/shareit/request/controller/RequestController.java
> +                                         @RequestParam(required = false, defaultValue = "0") @Min(0) int from,
done

2024-03-08 10:38 UTC, VadimZharkov approved these changes

2024-03-08 19:05 UTC, merged